on:
  push:
    branches:
      - master
      - main

name: Docs
env:
  RUSTFLAGS: -D warnings

jobs:
  docs:
    name: Build and deploy documentation
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build rustdoc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features
      - name: Organize
        run: |
          mkdir target/gh-pages
          mv target/doc target/gh-pages/rustdoc
          touch target/gh-pages/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/gh-pages
